name: Rust CD

on:
  push:
    branch: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build -t password-manager:latest .

      - name: Run Docker Container
        run: |
          docker stop password-manager-container || true
          docker rm password-manager-container || true
          docker run -d --name password-manager-container -p 8080:8080 password-manager:latest

      - name: List Containers
        run: docker ps -a

      - name: Show logs for the container
        run: docker logs password-manager-container