name: Cleanup Workflow Runs

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Delete Old Workflow Runs
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          REPO="leonhard-leung/password-manager"
          BASE_URL="https://api.github.com/repos/$REPO/actions/runs"
          HEADERS="Authorization: token $GH_PAT"

          YESTERDAY=$(date -u -d "1 day ago" '+%Y-%m-%dT%H:%M:%SZ')

          echo "Deleting workflow runs created before $YESTERDAY"

          RUNS=$(curl -H "$HEADERS" "$BASE_URL?status=completed&per_page=100" | jq -r --arg YESTERDAY "$YESTERDAY" '.workflow_runs[] | select(.created_at < $YESTERDAY) | .id')

          for RUN_ID in $RUNS; do
            echo "Deleting run ID: $RUN_ID"
            curl -X DELETE -H "$HEADERS" "$BASE_URL/$RUN_ID"
          done
